### ISSUE TITLE
Link is 404

### ISSUE THREAD

**Issue by Ndolam** [rasatpc/Fvwm-KISe#1]
The title says it all.

**Comment by rasatpc** [comment]
Which link are you referring to? Is it one of the `Read` commands?

**Comment by rasatpc** [comment]
Were you able to install Fvwm3 or Fvwm2 before trying to run the Fvwm-KISe config? The config is not a stand-alone application.

**Comment by Ndolam** [comment]
The link was not working when I last tried to d/l.
The link which is there now,
    https://github.com/rasatpc/Fvwm-KISe/archive/refs/heads/main.zip
is working today.  So this can be closed.

**Comment by rasatpc** [comment]
There is also another site with images and download:
https://www.box-look.org/p/2095462
